name: Update Image List

on:
  push:
    paths:
      - 'dist/assets/photos/2024/san-francisco/**'

jobs:
  update-image-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci
    - name: Generate image list
      run: |
        ls -R dist/assets/photos/2024/san-francisco
        npm run generate-image-list
      env:
        CI: true
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add images.json
        git commit -m "Update images.json" -a || echo "No changes to commit"
        git push
